export default {
    carts: [],
    cart_meta: [],
    message: null,
    wishlist: [],
    loggedIn: null,
    is_favorite: Boolean,
    addresses: [],
    regions: [],
    locations: [],
    voucher: [],
    shipping: null,
    default_shipping: [],
    errors: [],
    notification: null,
    reviews: [],
    reviewsMeta: null,
    comments: [],
    loadn: false,
    images: [],
    showForm: false,
    states: [],
    walletBalance: 0,
    tableData: [],
    meta: null,
    currentBid: 0,
    number_of_bidders: 0
}